Debug

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -28,126 +28,130 @@ before_install:
   # ensure its timestamp is the correct one and not the one at the time of cloning
   - touch -d "$(git log -1 --date=iso --format=%cd Makefile)" Makefile
 
-jobs:
-  include:
-    - stage: Static Code Analysis
-      php: 7.2
-      install:
-        - composer install $COMPOSER_FLAGS
-      script:
-        - make autoreview --keep-going
+script:
+    - set -x
+    - get-infection-pr-flags
 
-    - &STANDARD_TEST_JOB
-      stage: Test
-      php: 7.2
-      env: DRIVER="xdebug"
-      install:
-        - if [ "$DEPS" == "LOW" ]; then composer update --prefer-lowest $COMPOSER_FLAGS; else composer install $COMPOSER_FLAGS; fi
-      before_script:
-          - rm /home/travis/.phpenv/shims/phpunit || true
-          - rm /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit
-          - |
-              if [[ "$DRIVER" == "pcov" ]]; then
-                echo > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini
-                git clone --single-branch --branch=v1.0.6 --depth=1 https://github.com/krakjoe/pcov
-                cd pcov
-                phpize
-                ./configure
-                make clean install
-                echo "extension=pcov.so" > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/pcov.ini
-                cd $TRAVIS_BUILD_DIR
-              fi
-      script:
-        - if [[ "$DRIVER" == "xdebug" || "$DRIVER" == "none" ]]; then xdebug-enable; fi
-        - if [[ "$DRIVER" != "phpdbg" ]]; then $PHPUNIT_BIN; else phpdbg -qrr $PHPUNIT_BIN; fi
-        - |
-          if [[ "$DEPS" == "LOW" ]]; then
-            ./tests/e2e_tests bin/infection;
-          else
-            make compile;
-            ./tests/e2e_tests build/infection.phar;
-          fi
-        - if [[ "$DRIVER" == "none" ]]; then xdebug-disable; fi
-        - |
-          INFECTION_PR_FLAGS=$(get-infection-pr-flags);
-          echo "INFECTION_PR_FLAGS=$INFECTION_PR_FLAGS";
-
-          if [[ "$DRIVER" != "phpdbg" ]]; then
-            bin/infection $INFECTION_FLAGS $INFECTION_PR_FLAGS;
-          else
-            phpdbg -qrr bin/infection $INFECTION_FLAGS $INFECTION_PR_FLAGS;
-          fi
-
-      after_success:
-        - bash <(curl -s https://codecov.io/bash)
-
-    -
-      <<: *STANDARD_TEST_JOB
-      php: 7.3
-      env: DRIVER="xdebug"
-
-    -
-      <<: *STANDARD_TEST_JOB
-      php: 7.3
-      env: DRIVER="phpdbg"
-
-    - <<: *STANDARD_TEST_JOB
-      php: 7.3
-      env: DRIVER="pcov"
-
-    - <<: *STANDARD_TEST_JOB
-      php: 7.3
-      env: DRIVER="none"
-
-    -
-      <<: *STANDARD_TEST_JOB
-      php: 7.3
-      env: DEPS="LOW" DRIVER="xdebug"
-
-    -
-      <<: *STANDARD_TEST_JOB
-      php: 7.4snapshot
-      env: DRIVER="phpdbg"
-
-    -
-      <<: *STANDARD_TEST_JOB
-      php: nightly
-      env: DRIVER="phpdbg"
-
-      script:
-        # We don't have xdebug on the nightly build, so we always run with phpdbg.
-        - make compile;
-        - ./tests/e2e_tests build/infection.phar;
-        - phpdbg -qrr $PHPUNIT_BIN
-        - |
-          INFECTION_PR_FLAGS=$(get-infection-pr-flags);
-          phpdbg -qrr bin/infection $INFECTION_FLAGS $INFECTION_PR_FLAGS;
-
-    - stage: Deploy
-      php: 7.2
-      install:
-        - composer install --no-dev $COMPOSER_FLAGS
-      script:
-        make compile;
-      before_deploy:
-        - echo $DECRYPT_KEY | gpg --passphrase-fd 0 .ci/keys.asc.gpg
-        - gpg --batch --yes --import .ci/keys.asc
-        - echo $SIGN_KEY | gpg --passphrase-fd 0 -u C5095986493B4AA0 --armor --detach-sig build/infection.phar
-
-      deploy:
-        provider: releases
-        api_key:
-          secure: JtdvJBE2ARf6VWN5KlXAburz3FZMriiXBHEdeIocHePBAzgYW7tVMksJR5N3azrE3KjhftMEukXtA1k5VfAGdLCSm6nKGsZwolkd24ryG7PYNuAdFWfbau8QQXn6aLFesF2lkTq89+PqxAdVjwXNgFA7ble3vL66Ogabff6gov6QwT9vDrTqwLmWNGwbt9QB32IE9yVPjW/3lk4MAkMHtKDr2DElyeT2CRRuPuUCA+zNwoGG95wqLAD/RwjsqR3GjotzDKrldqog9jU2OQptUc3BgdKlYR1AzdknxJYnT7a5CRVdmSOEfD9IrDqlYEzn9pHav+Sk4KD2KNKsALQGk/w16BqncN2uyOexUTzXvnDd27G4ZYy+1OsXMdYMhF5ffwj7EqNLm8XfLPtHHV0/FUJY9kkrbf9+wQVjDQmMJLLIiBSt3vuY0ya5SVW8thtjlF2j67smamNe4hDhditBipto+9Y5vI4AYhcm4CQlqP8BVbw3/LgGAl/dJR5ohM7PFZH3EUE1AojBaEXfUymlICdFVZFJbB0D/AM8jSqNmWBQu9QX3MURhT5xLSwc+kir2izQaEo/GQz79AifqkUJgSCzpRUJntCN8A7yk1uxDZDONbINF3ReuF+nqu7GMksgKZLCGbOIaBl9of24K5BeTqxgcEykiHFFY7X9QdI3Dyo=
-        file:
-          - build/infection.phar
-          - build/infection.phar.asc
-        skip_cleanup: true
-        on:
-          tags: true
-          repo: infection/infection
-
-  allow_failures:
-    - php: nightly
-      env: DRIVER="phpdbg"
-    - php: 7.4snapshot
-      env: DRIVER="phpdbg"
+#jobs:
+#  include:
+#    - stage: Static Code Analysis
+#      php: 7.2
+#      install:
+#        - composer install $COMPOSER_FLAGS
+#      script:
+#        - make autoreview --keep-going
+#
+#    - &STANDARD_TEST_JOB
+#      stage: Test
+#      php: 7.2
+#      env: DRIVER="xdebug"
+#      install:
+#        - if [ "$DEPS" == "LOW" ]; then composer update --prefer-lowest $COMPOSER_FLAGS; else composer install $COMPOSER_FLAGS; fi
+#      before_script:
+#          - rm /home/travis/.phpenv/shims/phpunit || true
+#          - rm /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit
+#          - |
+#              if [[ "$DRIVER" == "pcov" ]]; then
+#                echo > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini
+#                git clone --single-branch --branch=v1.0.6 --depth=1 https://github.com/krakjoe/pcov
+#                cd pcov
+#                phpize
+#                ./configure
+#                make clean install
+#                echo "extension=pcov.so" > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/pcov.ini
+#                cd $TRAVIS_BUILD_DIR
+#              fi
+#      script:
+#        - if [[ "$DRIVER" == "xdebug" || "$DRIVER" == "none" ]]; then xdebug-enable; fi
+#        - if [[ "$DRIVER" != "phpdbg" ]]; then $PHPUNIT_BIN; else phpdbg -qrr $PHPUNIT_BIN; fi
+#        - |
+#          if [[ "$DEPS" == "LOW" ]]; then
+#            ./tests/e2e_tests bin/infection;
+#          else
+#            make compile;
+#            ./tests/e2e_tests build/infection.phar;
+#          fi
+#        - if [[ "$DRIVER" == "none" ]]; then xdebug-disable; fi
+#        - |
+#          INFECTION_PR_FLAGS=$(get-infection-pr-flags);
+#          echo "INFECTION_PR_FLAGS=$INFECTION_PR_FLAGS";
+#
+#          if [[ "$DRIVER" != "phpdbg" ]]; then
+#            bin/infection $INFECTION_FLAGS $INFECTION_PR_FLAGS;
+#          else
+#            phpdbg -qrr bin/infection $INFECTION_FLAGS $INFECTION_PR_FLAGS;
+#          fi
+#
+#      after_success:
+#        - bash <(curl -s https://codecov.io/bash)
+#
+#    -
+#      <<: *STANDARD_TEST_JOB
+#      php: 7.3
+#      env: DRIVER="xdebug"
+#
+#    -
+#      <<: *STANDARD_TEST_JOB
+#      php: 7.3
+#      env: DRIVER="phpdbg"
+#
+#    - <<: *STANDARD_TEST_JOB
+#      php: 7.3
+#      env: DRIVER="pcov"
+#
+#    - <<: *STANDARD_TEST_JOB
+#      php: 7.3
+#      env: DRIVER="none"
+#
+#    -
+#      <<: *STANDARD_TEST_JOB
+#      php: 7.3
+#      env: DEPS="LOW" DRIVER="xdebug"
+#
+#    -
+#      <<: *STANDARD_TEST_JOB
+#      php: 7.4snapshot
+#      env: DRIVER="phpdbg"
+#
+#    -
+#      <<: *STANDARD_TEST_JOB
+#      php: nightly
+#      env: DRIVER="phpdbg"
+#
+#      script:
+#        # We don't have xdebug on the nightly build, so we always run with phpdbg.
+#        - make compile;
+#        - ./tests/e2e_tests build/infection.phar;
+#        - phpdbg -qrr $PHPUNIT_BIN
+#        - |
+#          INFECTION_PR_FLAGS=$(get-infection-pr-flags);
+#          phpdbg -qrr bin/infection $INFECTION_FLAGS $INFECTION_PR_FLAGS;
+#
+#    - stage: Deploy
+#      php: 7.2
+#      install:
+#        - composer install --no-dev $COMPOSER_FLAGS
+#      script:
+#        make compile;
+#      before_deploy:
+#        - echo $DECRYPT_KEY | gpg --passphrase-fd 0 .ci/keys.asc.gpg
+#        - gpg --batch --yes --import .ci/keys.asc
+#        - echo $SIGN_KEY | gpg --passphrase-fd 0 -u C5095986493B4AA0 --armor --detach-sig build/infection.phar
+#
+#      deploy:
+#        provider: releases
+#        api_key:
+#          secure: JtdvJBE2ARf6VWN5KlXAburz3FZMriiXBHEdeIocHePBAzgYW7tVMksJR5N3azrE3KjhftMEukXtA1k5VfAGdLCSm6nKGsZwolkd24ryG7PYNuAdFWfbau8QQXn6aLFesF2lkTq89+PqxAdVjwXNgFA7ble3vL66Ogabff6gov6QwT9vDrTqwLmWNGwbt9QB32IE9yVPjW/3lk4MAkMHtKDr2DElyeT2CRRuPuUCA+zNwoGG95wqLAD/RwjsqR3GjotzDKrldqog9jU2OQptUc3BgdKlYR1AzdknxJYnT7a5CRVdmSOEfD9IrDqlYEzn9pHav+Sk4KD2KNKsALQGk/w16BqncN2uyOexUTzXvnDd27G4ZYy+1OsXMdYMhF5ffwj7EqNLm8XfLPtHHV0/FUJY9kkrbf9+wQVjDQmMJLLIiBSt3vuY0ya5SVW8thtjlF2j67smamNe4hDhditBipto+9Y5vI4AYhcm4CQlqP8BVbw3/LgGAl/dJR5ohM7PFZH3EUE1AojBaEXfUymlICdFVZFJbB0D/AM8jSqNmWBQu9QX3MURhT5xLSwc+kir2izQaEo/GQz79AifqkUJgSCzpRUJntCN8A7yk1uxDZDONbINF3ReuF+nqu7GMksgKZLCGbOIaBl9of24K5BeTqxgcEykiHFFY7X9QdI3Dyo=
+#        file:
+#          - build/infection.phar
+#          - build/infection.phar.asc
+#        skip_cleanup: true
+#        on:
+#          tags: true
+#          repo: infection/infection
+#
+#  allow_failures:
+#    - php: nightly
+#      env: DRIVER="phpdbg"
+#    - php: 7.4snapshot
+#      env: DRIVER="phpdbg"
